### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by phadej**
Sorry for very major rewrite, but I think it's better to update already existing package then roll my own :)

### CODE REVIEW

**Comment by richsmith92** [comment]
@phadej I get this error after cabal install in fresh sandbox:

```
src/Data/Hashable/Time.hs:54:44:
    No instance for (Hashable Pico)
      arising from a use of ‘hashWithSalt’
    In the expression:
      salt `hashWithSalt` h `hashWithSalt` m `hashWithSalt` s
    In an equation for ‘hashWithSalt’:
        hashWithSalt salt (TimeOfDay h m s)
          = salt `hashWithSalt` h `hashWithSalt` m `hashWithSalt` s
    In the instance declaration for ‘Hashable TimeOfDay’
cabal: Error: some packages failed to install:
```

Otherwise, thanks a lot for the rewrite! What was the rationale behind replacing deriving? Support for older versions?

**Comment by phadej** [comment]
Oops. The `MIN_VERSION_hashable` macro was tricky. I force pushed a fix.

**Comment by richsmith92** [comment]
Now it builds for me. Since I don't have any CI stuff set up, that's enough.

**Comment by phadej** [comment]
I can make a .travis.yaml for you, with some ok-ish defaults, if you like to click thru? For reference: https://github.com/isomorphism/these/issues/33

**Comment by richsmith92** [comment]
@phadej can I make you a maintainer? Must be simpler this way

**Comment by phadej** [comment]
With travis it doesn't work, as you need to be an owner of the repository at github to setup it :(

**Comment by richsmith92** [comment]
Hmm, I don't know what's github way for transferring repo. Fork and edit .cabal file? Or you can just make another pull request.

**Pull request merged**
