### PR TITLE
Make it build with ghc 8.2

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by erikd** [comment]
Thanks!

**Comment by richsmith92** [comment]
@erikd I'll release new version shortly, but unfortunately I don't have Travis integration set up to check the changes. If you feel like contributing the `.travis.yml`, be welcome.

**Comment by richsmith92** [comment]
Correction: we actually do have `.travis.yml`, it just didn't run the build. I don't really know how to make it work, and not particularly interested to spend my time on this. I'd be happy to give up my maintainership to anyone willing to take over. 

Meanwhile, released new version on hackage.

**Comment by erikd** [comment]
If you *really* want to give it up, you can transfer it to me.

**Comment by richsmith92** [comment]
Thanks. Probably I'll just ask on haskell reddit about this some day.

**Pull request merged**
